apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f postgres/docker-compose.yml -f app/docker-compose.yml -f myworker/docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8080
  selector:
    io.kompose.service: app
