apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikroserwis-b
  template:
    metadata:
      labels:
        app: mikroserwis-b
    spec:
      containers:
      - name: mikroserwis-b
        image: janjus/mikroserwis-b:1.2
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_URL
            value: mongodb://mongo-service:27017/db
