apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-a
spec:
  selector:
    matchLabels:
      app: mikroserwis-a
  template:
    metadata:
      labels:
        app: mikroserwis-a
    spec:
      containers:
      - name: mikroserwis-a
        image: janjus/mikroserwis-a:1.0
        resources:
          requests:
              memory: "64Mi"
              cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: B_URL
          value: http://mikroserwis-b-service:3000
